### ISSUE TITLE
Active Ender Beecon causes massive FPS drops

### ISSUE THREAD

**Issue by g0urra** [Team-Resourceful/ResourcefulBees#243] opened 2021-05-16 13:39 UTC
**Describe the bug**
Having an active Ender Beecon causes massive FPS drops, having it passive does not cause this.

**To Reproduce**
1. Place an Ender Beecon and fill with Honey to start
2. Running any active buff causes FPS drops when Beecon is active
3. Changing to passive mode returns the game to normal

**Expected behavior**
Not to cause massive FPS drops when using an active Ender Beecon.

**Screenshots or Crash Logs**
https://spark.lucko.me/lGiBycgHRt

**please complete the following information:**
 - Forge Version 1.16.5 - 36.1.13
 - Mod Version 0.6.7.2b

**Additional context**
None

**Comment by TemperedFool** [comment] 2021-05-16 13:47
I'll inject that this is in Enigmatica 6, I'm assuming either 0.4.10 or 0.4.12.

**Comment by g0urra** [comment] 2021-05-16 13:47
Correct, 0.4.10.

**Comment by Epic428** [comment] 2021-05-16 19:21
We’ve had other reports of FPS drops from the Ender beecon but can’t reproduce it. The beecon uses the same code as the vanilla beacon

**Comment by g0urra** [comment] 2021-05-17 17:34
> We’ve had other reports of FPS drops from the Ender beecon but can’t reproduce it. The beecon uses the same code as the vanilla beacon

I'd like to invite you to my server then so you can experience it yourself.

**Comment by Epic428** [comment] 2021-05-24 13:21
I'd like you to know that render code is client side code only and as such it doesn't matter whether you're connected to a server or not bc the code is only ever run on the client. as such this is a video of my FPS with multiple beecons vs multiple beacons

https://imgur.com/SnrPTOc

**Comment by Epic428** [comment] 2021-05-24 13:23
oh and it also doesn't matter what pack either. unless some other mod is fucking up render in which case it isn't us

**Comment by g0urra** [comment] 2021-05-24 16:47
Are your Beecons active (gives bee buffs) or passive? It happens when it's active but not when passive. The stutter persist when not looking at the Beecon.

**Comment by Vaerys-Dawn** [comment] 2021-05-24 21:33
I did notice some minor fps drops in my test world with a beecon active, I think I know the cause, it's all the particles given off by the beecon when the effects are applied, I'll change it so that the effect bubbles aren't applied which should help fps

**Comment by Vaerys-Dawn** [comment] 2021-05-24 21:35
the fix for this will take a little bit to get out as we're working on a MASSIVE update, for now i'd recommend turning down particles

**Comment by g0urra** [comment] 2021-05-29 16:02
Turning down particles didn't help much, but good to hear you found a fix.

**Comment by Epic428** [comment] 2021-05-29 18:55
Yeah I’m gonna have to assume that any FPS drops are a hardware issue. If particles cause FPS issues then that’s a hardware issue. I’m gonna leave this open for now but I’d really like to close as can not reproduce. In dawns case a 5 fps drop isn’t the same as someone else’s FPS tanking. But depending on hardware it very well could be

**Comment by g0urra** [comment] 2021-05-30 17:52
Just as a side note, I have noticed some of the debugging you've done have been done in single player. It might be because I play on a server, have you been able to replicate it?

**Comment by Jafner** [comment] 2021-08-25 17:28
I would like to +1 this issue, and my case is pretty extreme.
Hardware: 
* Ryzen 3700X
* RTX 2080 Super
* 12GB RAM dedicated to the client

Software:
* Enigmatica 6 0.5.6
* Win 10 64-bit
* Java 8u301
 
Sitting in my base with four passive Beecons, I get a consistent ~120 fps. 
Activating one Beecon reduces that to ~30 fps.
Activating a second Beecon further reduces the fps to 11. 
Reducing all my video settings to minimum (Graphics: fast, Smooth lighting: minimum, Clouds: off, Particles: minimal) has no effect on this reduction.

Further, a vanilla beacon has no such effect on framerate.
Taking the Beecon away from any bees significantly mitigates the FPS reduction. Away from any bees, my framerate drops by only 10-15, rather than 100+.

**Comment by Vaerys-Dawn** [comment] 2021-08-25 23:48
fixed in 0.9.9.2

**Closed as completed by Vaerys-Dawn** 2021-08-25 23:48 UTC
Labels: 1.16.5
