### ISSUE TITLE
Hoppers under hives only pick up 1 honeycomb when the full hive is harvested with shears

### ISSUE THREAD

**Issue by winauer** [Team-Resourceful/ResourcefulBees#160] opened 2021-02-16 18:37 UTC
**Describe the bug**
Hoppers under hives only pick up 1 honeycomb when the full hive is harvested with shears.
Vanilla 1.15 had the same bug, but it was fixed in 1.15.2. See https://bugs.mojang.com/browse/MC-165695

**To Reproduce**
1. Place hopper under full vanilla hive or nest
2. Use shears
-> All 3 honeycombs are picked up by the hopper

1. Place hopper under full hive from the Resourceful Bees mod
2. Use shears
-> Only one comb is picked up, the rest fly away

**Expected behavior**
A clear and concise description of what you expected to happen:

Modded hives working like vanilla hives/nests

**Screenshots or Crash Logs**
If applicable, add screenshots or crash logs to help explain your problem.

N.A.

**please complete the following information:**
 - Forge Version 1.16.5 - 36.0.42
 - Mod Version 1.16.5 - 0.5.9_3b

**Comment by Epic428** [comment] 2021-02-23 02:42
I'll have to revisit this another time. I looked through our stuff and vanilla to see what special thing they do for hoppers but I can't find anything that's different.

**Comment by desagas** [comment] 2021-03-07 17:49
I am pretty sure that combs pop off in random directions in both RB and vanilla. I am pretty sure this was an intended mechanic in Vanilla, and has been that way since they were first introduced in 1.15.

**Comment by Vaerys-Dawn** [comment] 2021-03-07 17:54
considering not a bug, Closing

**Closed as completed by Vaerys-Dawn** 2021-03-07 17:54 UTC
Labels: Need Info
