### ISSUE TITLE
Baby Bee Disappears

### ISSUE THREAD

**Issue by maxhg521** [Team-Resourceful/ResourcefulBees#118] opened 2021-01-11 19:32 UTC
**Describe the bug**
I breed two bees together; I put the baby bee in a safe enclosed space and after a bit the baby bee disappears

**To Reproduce**
1. Breed bees
2. put baby bee in jar
3. releases bee in enclosed space
4. baby disappears

**Expected behavior**
baby is supposed to grow up 

**please complete the following information:**
 - Forge Version 35.1.29
 - Mod Version ResourcefulBees1.16.3-1.16.4-0.5.7b.jar

**Additional context**
its happed right in front of my eyes. I had  500 secs left on the bee growth timer and then the bee just disappears

**Comment by Vaerys-Dawn** [comment] 2021-01-11 20:18
If your enclosure has a solid roof (aka made of wood/stone etc) baby bees will suffocate, this is a vanilla bug, the issue is that the baby hitbox's eye level is above the top of the hitbox and when they fly into the roof they suffocate. 

If that's not the case please let us know

**Comment by maxhg521** [comment] 2021-01-12 01:33
> If your enclosure has a solid roof (aka made of wood/stone etc) baby bees will suffocate, this is a vanilla bug, the issue is that the baby hitbox's eye level is above the top of the hitbox and when they fly into the roof they suffocate.
> 
> If that's not the case please let us know

yea I had that happen earlier so I tried glass roof and a trap door roof under the glass roof but in both occasions the bees have disappeared

**Comment by Vaerys-Dawn** [comment] 2021-01-12 03:55
can you give a screenshot of the enclosure?

**Comment by SophisticaSean** [comment] 2021-01-19 23:16
This happens to me routinely if there is no nest/hive in their enclosure. try adding a hive/nest that they can pop in and out of and that should remedy the issue. Not sure why this happens, I'm assuming they're despawning for some reason cuz I never hear bee damage sounds. The bee despawning can be replicated by holding out the bee's breeding item and then just afking in their enclosure for ~20 minutes. When I come back it seems all but 1 bee despawns.

**Comment by Epic428** [comment] 2021-01-19 23:21
bees are designed to despawn after 10 consecutive minutes of not being within a 10 block range of a hive/apiary. you can also give bees custom names with nametags to keep them from despawning.

**Comment by Cavecanem** [comment] 2021-01-23 16:12
They seem to suffocate with (with at least some) glass blocks that aren't vanilla. I've tried with Panzer Glass from Engineer's Decor and Framed Glass from Create with the same results. Regular glass seems to work fine though.

**Comment by Vaerys-Dawn** [comment] 2021-01-28 19:10
baby bees suffocating in roofs will be fixed in the next major patch, it's a vanilla bug that mojang say incorrectly is fixed,

Mojang's code
```Java
   protected float getStandingEyeHeight(Pose p_213348_1_, EntitySize p_213348_2_) {
      return this.isChild() ? p_213348_2_.height * 0.5F : p_213348_2_.height * 0.5F;
   }
```

Our mixin fix
```Java
    @Override
    protected float getStandingEyeHeight(@NotNull Pose pose, EntitySize size) {
        return this.isChild() ? size.height * 0.25F : size.height * 0.5F;
    }
```

**Closed as completed by Vaerys-Dawn** 2021-01-28 19:10 UTC

**Comment by Vaerys-Dawn** [comment] 2021-02-03 01:57
update to 0.5.9_1b
