### ISSUE TITLE
Elite Centrifuge cannot be accessed with empty hand.

### ISSUE THREAD

**Issue by AdamNisbett** [Team-Resourceful/ResourcefulBees#193] opened 2021-03-27 18:29 UTC
The Elite Centrifuge (and maybe other centrifuges - haven't tested) doesn't open the interface if right clicked with an empty hand.

**To Reproduce**
1. Create Elite multiblock centrifuge
2. right click with empty hand
3. nothing happens
4. right click with non-empty hand and interface opens.

**Expected behavior**
Centrifuge interface opens when right clicking with empty hand.

**please complete the following information:**
 - Forge-1.16.5-36.1.0
 - Mod Version 1.16.5-0.6.5b

**Additional context**
On Enigmatica 6 official server (Enigmatica 6 0.4.7 modpack)

**Comment by ThatGravyBoat** [comment] 2021-03-27 18:32
Make sure the multiblock is a valid multiblock and you are not holding down shift

**Comment by ThatGravyBoat** [comment] 2021-03-27 18:32
send a picture of your centrifuge

**Comment by AdamNisbett** [comment] 2021-03-27 20:12
I'm certain it was valid as I could access it when holding an item and I wasn't holding shift.

However I cannot reproduce the issue now, so not sure what was wrong.  Perhaps server TPS was lagging.

**Comment by AdamNisbett** [comment] 2021-03-28 21:27
OK - happened again.  Still not sure what the cause is.  Here's a screenshot though:
![image](https://user-images.githubusercontent.com/9061144/112768617-6a13de80-8fe2-11eb-926f-1f2f77876833.png)

Only notable difference between when it worked and didn't is that it has had combs and working on processing them when I'm unable to access both times.

**Comment by AdamNisbett** [comment] 2021-03-28 21:30
Nevermind.  Still unable to access with empty hand after processing finished. No idea what's the difference between when I can and can't access it.

**Comment by Epic428** [comment] 2021-03-28 21:40
```java
if (controller != null && controller.isValidStructure()) {
            if (hasCapability) {
                controller.getCapability(CapabilityFluidHandler.FLUID_HANDLER_CAPABILITY)
                        .ifPresent(iFluidHandler -> FluidUtil.interactWithFluidHandler(player, hand, world, pos, null));
            } else if (!player.isShiftKeyDown() && !world.isClientSide) {
                NetworkHooks.openGui((ServerPlayerEntity) player, controller, pos);
            }
            return ActionResultType.SUCCESS;
        } 
```


That’s the code for opening the GUI on the multiblock centrifuges. Casings use the same logic but call the GUI for the controller block. There’s nothing there that would prevent it from displaying when using an empty hand other than the multiblock being valid. Use /data get on the controller and check the nbt data. See if it’s showing as valid. If it’s not and it’s built correctly then we have a different bug.

**Comment by AdamNisbett** [comment] 2021-03-28 21:47
It's back to working again after waystoning back to see if I could figure out what you suggested.  Not sure if I'd be able to do that or not anyway as I'm playing on a server and don't have any particular admin command access.

However, the multiblock is certainly valid as I can easily open and use it when holding an item whenever this happens.  It is a modpack with a number of other mods, so perhaps code from some other mod is interfering? I may go ahead and link this issue on the Enigmatica issue tracker to see if they have any ideas.

**Comment by Epic428** [comment] 2021-04-13 22:08
Any more issues with this? Any logs generated yet that can be used to identify if the issue is related to the one referenced in the linked issue?

**Comment by AdamNisbett** [comment] 2021-04-13 22:34
I have not had the issue repeat since my last post, but I also haven’t been on the server much in the last couple weeks.

**Comment by Vaerys-Dawn** [comment] 2021-04-15 04:41
closing reason: CNR

**Closed as completed by Vaerys-Dawn** 2021-04-15 04:41 UTC
Labels: Can’t Reproduce, low priority
