### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Jvillacillo** [Team-Resourceful/ResourcefulBees#120] opened 2021-01-15 04:26 UTC
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**
Cannot run a server because of the Resourceful Bees mod.

**To Reproduce**
1. Start server
2. Server loading
3. Error occurred

**Expected behavior**
To load fine

**Screenshots or Crash Logs**
If applicable, add screenshots or crash logs to help explain your problem.
![image](https://user-images.githubusercontent.com/25965427/104681113-d010eb00-56ae-11eb-9653-be491705856e.png)

**please complete the following information:**
 - forge-1.16.4-35.1.29
 - ResourcefulBees1.16.3-1.16.4-0.5.7b

**Comment by Vaerys-Dawn** [comment] 2021-01-15 04:33
Could you please pastebin the entire server log and post it here?

**Comment by Vaerys-Dawn** [comment] 2021-01-15 04:34
It looks like something related to a custom bee failed to initialise properly

**Comment by Jvillacillo** [comment] 2021-01-15 04:34
Where should I paste it? just here?

**Comment by Jvillacillo** [comment] 2021-01-15 04:35
> Could you please pastebin the entire server log and post it here?

https://paste.shockbyte.com/inasifofurexajuneqel

It's a very long log, but have at it

**Comment by Jvillacillo** [comment] 2021-01-15 04:36
The crash starts at line: 928

**Comment by Vaerys-Dawn** [comment] 2021-01-15 06:36
are you running a modpack? this seems to be caused by a broken .json file, this can be something as simple as a .json file that isn't a bee in the bee folder or something annoying like a missing comma

**Comment by Jvillacillo** [comment] 2021-01-15 06:39
> are you running a modpack? this seems to be caused by a broken .json file, this can be something as simple as a .json file that isn't a bee in the bee folder or something annoying like a missing comma

Yes, I am running the modpack: All The Mods 6

**Comment by Vaerys-Dawn** [comment] 2021-01-15 06:49
have you edited any of the bees in their json files, 

also iirc 0.5.7b has issues fixed in the latest version, ATM6 seems to still ship with an out of date version that doesn't have the performance fixes added to help servers.

updating probably won't fix the issue as it seems to stem from a broken json file

**Comment by Jvillacillo** [comment] 2021-01-15 06:51
No I havent, but I would like to know what I can edit on the json file(s) to fix it

**Comment by Vaerys-Dawn** [comment] 2021-01-15 06:55
are you on the discord? https://discord.com/invite/KGRgpMx9ZA if you can ping me @ Dawn Felstar i can have a crack at figuring out what's wrong, going to have to inspect the json files individually :T

**Comment by Jvillacillo** [comment] 2021-01-15 06:57
> are you on the discord? https://discord.com/invite/KGRgpMx9ZA if you can ping me @ Dawn Felstar i can have a crack at figuring out what's wrong, going to have to inspect the json files individually :T

I do, I'm not at my computer atm but I'll hop on in a few mins

**Comment by Vaerys-Dawn** [comment] 2021-01-28 19:08
crash was caused by empty .json file.

**Closed as completed** 2021-01-28 19:08 UTC
