### ISSUE TITLE
'Valid apiary block' tooltip is annoying

### ISSUE THREAD

**Issue by LemonShaped** [Team-Resourceful/ResourcefulBees#264] opened 2021-06-29 19:59 UTC
### Bug Description

All valid apiary blocks always say that they are in their tooltip.
This is kind of annoying especially since this includes so many common blocks.
![image](https://user-images.githubusercontent.com/64607380/123858479-7a0dc800-d91b-11eb-8af5-b41b24b9bfca.png)

### How to Reproduce?

Hover over any valid apiary block in inventory or jei

### Expected Behavior

Either a config option to turn this tooltip off,
or only show it when advanced tooltips is on.

### Version

0.6.7.2b

### Mod Loader Version

1.16.5 - 36.1.31

### Logs or additional context

I am playing the All the mods 6 modpack

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment] 2021-06-29 20:03
Ummmm that is not something that is caused by us. That’s a very interesting bug however

**Comment by Pdiddy973** [comment] 2021-06-30 19:22
This was added into ATM via kube, not a bug

https://www.github.com/AllTheMods/ATM-6/tree/master/kubejs%2Fclient_scripts%2Fclient_scripts.js

Line 371

**Comment by Epic428** [comment] 2021-07-04 09:26
Closing this due to being a feature added by ATM6 using scripts. Also diddy you might wanna look into having this info added to the advanced tool tips if at all possible. Might be a better solution.

**Closed as completed by Epic428** 2021-07-04 09:26 UTC
Labels: bug
