### ISSUE TITLE
Manual Centrifuge able to process honeycomb blocks

### ISSUE THREAD

**Issue by smbarbour** [Team-Resourceful/ResourcefulBees#216] opened 2021-04-12 02:08 UTC
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**
Manual Centrifuge is able to process honeycomb blocks

**To Reproduce**
1. Craft a honeycomb block
2. Add honeycomb block to Manual Centrifuge
3. Add enough empty bottles to reach at least 9
4. Activate centrifuge

**Expected behavior**
Honeycomb blocks should require multiblock centrifuge

**Screenshots or Crash Logs**
If applicable, add screenshots or crash logs to help explain your problem.

**please complete the following information:**
 - Forge Version [e.g. '1.15.2 - 31.2.5'] 1.16.5-36.1.2
 - Mod Version [e.g. '0.2.0'] 0.6.5b

**Additional context**
Additional related bug:  When honey production is successful, it produces 9 honey bottles and consumes 1 empty bottle, resulting in the materialization of 8 new bottles.

**Comment by Epic428** [comment] 2021-04-12 02:09
Only the Multiblock centrifuge is able to process H=honeycomb blocks by design

**Comment by smbarbour** [comment] 2021-04-12 02:09
That's why this is a bug.

**Comment by Epic428** [comment] 2021-04-12 02:09
wait it is accepting honeycomb blocks????

**Comment by smbarbour** [comment] 2021-04-12 02:10
Yep.  If you would like, I can record a video of this happening.

**Comment by Epic428** [comment] 2021-04-12 02:10
I misread your post at first
......
Ugh now I have to test this shit bc that's not supposed to happen and was designed that way

**Comment by Epic428** [comment] 2021-04-12 02:11
which modpack is this in by chance? maybe the pack dev created recipes for it

**Comment by smbarbour** [comment] 2021-04-12 02:11
Sky Bees

**Comment by Epic428** [comment] 2021-04-12 02:12
Ok I have to load the pack up and I can test, but first let me verify with ATM6 bc if it doesn't happen there then it's a change by the pack dev and not an issue with our machine, which the more that I think about it, it sounds like that may be the case

**Comment by sharpskull2** [comment] 2021-04-12 02:18
Hey there, I just tested this in a default environment (Just forge 1.16.5 - 36.1.2 and resourceful bees)
The honey combs blocks are able to be processed in the manual centrifuge, so it does not appear to be a mod pack bug
:)

**Comment by Epic428** [comment] 2021-04-12 02:20
yeah no I think I may have to yell at dawn for breaking this feature. I need to verify with git blame first. I found the issue in our code

**Comment by sharpskull2** [comment] 2021-04-12 02:21
Also in addition to this issue, the vanilla honeycomb block (made with 4 vanilla combs) produces a 9x output compared to a singular comb

**Comment by Epic428** [comment] 2021-04-12 02:22
yeah it's bc of how the multiblock is setup. I can look at changing it but tbh I probably won't bc combs are infinite and it isn't really "game breaking"

**Comment by Epic428** [comment] 2021-04-12 02:45
This has been fixed in dev

**Closed as completed by Epic428** 2021-04-12 02:45 UTC
