### ISSUE TITLE
JEI Search shows Bee ID, not localized bee name

### ISSUE THREAD

**Issue by ReillyBrogan** [Team-Resourceful/ResourcefulBees#114] opened 2021-01-09 04:33 UTC
**Describe the bug**
I just noticed something interesting. It seems that when you search JEI for a specific bee search results are indexed by the Bee ID, not the localized bee name. This leads to some unexpected behavior for people who are searching for bees who are not aware of this quirk. 

**To Reproduce**
1. Have a bee with a different localized name than the bee ID (example from ATM6 `"entity.resourcefulbees.skeleton_bee" : "Spooky Bee"`
2. Search JEI for "Spooky Bee"
3. See that "Spooky Bee" doesn't have any results.
4. (if you're a normal user at this point you're probably confused)

**Expected behavior**
"Spooky Bee" should show the entry for that bee

**please complete the following information:**
 - Forge Version 1.16.4-35.1.29
 - Mod Version 0.5.8b

**Comment by ReillyBrogan** [comment] 2021-01-31 03:26
@Vaerys-Dawn I don't understand why you closed this. Do you mean this has been fixed in the repo or that you were not able to reproduce it?

**Comment by ThatGravyBoat** [comment] 2021-01-31 03:29
They put the cant reproduce label, as they couldn't reproduce the bug you described.

**Comment by ReillyBrogan** [comment] 2021-01-31 03:53
@ThatGravyboat Except it's still easily reproduced on the latest version (as of this post) of Forge, JEI, and Resourceful Bees so that seems unlikely. Also, one would expect a request for additional information if the maintainer either did not understand the issue or the steps to reproduce were not clear enough.

**Comment by Epic428** [comment] 2021-01-31 03:58
I will check it out in the morning. But I would hazard a guess that the issue would lie on JEI side. Which confuses me bc I would think that jei handles searching by both ID and the translation

**Comment by ThatGravyBoat** [comment] 2021-01-31 04:04
I just tested and also couldn't reproduce it, I searched up "spooky bee" and it showed the skeleton bee with the id of skeleton bee but its localized name was spooky bee so yeah....

**Comment by Vaerys-Dawn** [comment] 2021-01-31 04:05
i marked  could not repro and closed it because in my testing it returned based on both id and local name

**Comment by Epic428** [comment] 2021-01-31 04:06
What about on a server? Just out of curiosity

**Comment by ReillyBrogan** [comment] 2021-01-31 04:27
This is what I see when I search for "spooky" in a fresh ATM6 1.5.0 instance:
![image](https://user-images.githubusercontent.com/4309817/106374433-2d609980-6349-11eb-8a6d-89c13ef221d0.png)

Note that while the items are probably indexed by localized name the custom bee entry is missing. That bee only shows up when you search for "Skeleton"
![image](https://user-images.githubusercontent.com/4309817/106374445-410c0000-6349-11eb-9883-cfb5c8e76c14.png)

Single player tested.

**Comment by ThatGravyBoat** [comment] 2021-01-31 04:32
what version of jei do you have?

**Comment by ReillyBrogan** [comment] 2021-01-31 04:53
@ThatGravyboat The latest, `jei-1.16.4-7.6.1.65`

**Comment by ReillyBrogan** [comment] 2021-01-31 04:54
I tested with the version of Forge in ATM6 (`36.0.9`), as well as the absolute latest release (`36.0.13`).

**Comment by Epic428** [comment] 2021-01-31 04:58
I’ll update forge and jei in dev to latest versions and test it again to make sure something didn’t change. It’ll be about 7 hrs before I can do that though

**Comment by Pdiddy973** [comment] 2021-01-31 07:26
this also happens in ATM6 1.4.1 forge 35.1.36, JEI 6.1.1.11, Bees .5.8b

**Comment by Epic428** [comment] 2021-01-31 07:27
Weird. I’ll def do some playing around with it when I get home and figure out why it’s happening but good to know someone else is able to reproduce

**Comment by Epic428** [comment] 2021-01-31 13:08
I can confirm that in dev it works perfectly fine without issue as seen below
![2021-01-31_07 37 29](https://user-images.githubusercontent.com/291578/106384839-0468f480-639b-11eb-810d-02992822b409.png)

However I can also confirm that it does not work properly outside of dev (well in ATM6 at least, not sure about standalone) as seen below
![2021-01-31_08 06 55](https://user-images.githubusercontent.com/291578/106384892-5ad63300-639b-11eb-90ae-f63d3105b647.png)
![2021-01-31_08 07 05](https://user-images.githubusercontent.com/291578/106384897-5d388d00-639b-11eb-8b35-6d2b48e8e891.png)

To be honest I'm not exactly sure why it works in dev but not in production. It's worth looking into but not a high priority though annoying.

**Comment by Epic428** [comment] 2021-01-31 14:18
OK so I did some further testing and even updated dev environment to latest forge, mc, and JEI. I can ONLY reproduce the issue in ATM6, I haven't tested E6 to see if the issue is present there as well. I tried an isolated production setup with just us and jei on latest forge/mc and could not reproduce. I thought maybe it was lang files in the config folder and tested those in dev and could not reproduce.

So best guess at this point is it is a forge issue, jei issue, or another mod conflict. Not really sure what else to do to test further. It is annoying for sure but low on priority. I will leave this open in case anyone else wants to look into it further or more info can be provided.

**Comment by ReillyBrogan** [comment] 2021-01-31 20:49
* I went ahead and created a new clean instance with the same versions of Forge, JEI, and ResourcefulBees that ATM6 uses and indeed the issue was not present there. I tried copying over the ATM6 RB config files and the issue was still not present.
* Going in batches I disabled every mod that wasn't Forge, JEI, or ResourcefulBees from a fresh ATM6 instance and the issue was still present. This rules out a mod conflict.
* (took a brief moment to marvel at how quickly Minecraft loads with just those 3 mods enabled)
* Diffed the forge and JEI configs between the ATM6 version and the "default" ones
* Finally found the culprit, `TooltipSearchMode = "REQUIRE_PREFIX"` in `jei-client.toml`.

Now, my understanding of this is that this option controls whether tooltip search is enabled or disabled, or requires a prefix to search (`#` usually). Default JEI setting is that it is enabled and tooltips are searched.

I'm going to keep digging to find out how it's supposed to work but I would assume that this is not the way it's supposed to work for custom entries like this.

**Comment by TheSnowyChickens** [comment] 2021-02-11 04:54
Hello there,

I see that I am at the right place for the "there are no bees in JEI" issue. :D
I reloaded my test server (a small custom pack, ~70 mods) aaaaand the bees are gone from JEI and I can't bring them back. :(
(newest version of all the mods)

(I know, this comment is 0% helpful for the issue. ^^)

**Comment by Epic428** [comment] 2021-02-11 04:56
I don’t believe this is the same issue that you are experiencing. This particular issue is related to jei search not recognizing the translated names only the registry IDs which seems it’s Bc of tooltip searching.

**Comment by Epic428** [comment] 2021-02-11 04:57
Your issue is a strange one that comes and goes. But bees are added to jei as custom ingredients using jei. I’ve seen it happen on occasion but there’s nothing in logs to help identify a cause and restarting the game seems to resolve the issue

**Comment by Vaerys-Dawn** [comment] 2021-03-07 17:51
Closing as this is an issue seems to be "caused" by JEI custom ingredients, not really something we can fix

**Closed as completed by Vaerys-Dawn** 2021-03-07 17:51 UTC
Labels: bug, low priority
