### ISSUE TITLE
Bees won't go back to the apiarys

### ISSUE THREAD

**Issue by piterrk** [Team-Resourceful/ResourcefulBees#139] opened 2021-01-30 17:10 UTC
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**

**To Reproduce**
1. Build an apiary of level 1
2. Import a bee
3. When the count reaches 0, it produces honeycombs, but after that, the bee dont come back to de apiary

**Expected behavior**
The bee get back to the apiary to produce resources

**please complete the following information:**
 - Forge Version [e.g. '1.16.5 - 36.2.9']
 - Mod Version [e.g. '0.5.8b']

**Comment by Vaerys-Dawn** [comment] 2021-01-30 18:31
We do not currently know if 1.16.5 works properly with the 1.16.4 build, as such we need to identify that this bug is not caused by any other issues.

as you have provided little context and information could you please confirm these for me?
- is the bee unlocked? (there is a lock icon next to each bee in the apiary after importing, it needs to show an open padlock)
- does the bee leave the apiary?
- does the bee pollinate? (i.e does it spin on a flower and then gain particles)
- do regular nests and tiered hives work?
- are there any errors in the logs? if so can you post a pastebin with the error?

**Comment by Nix-23** [comment] 2021-02-01 05:34
I'm having the same problem in 1.16.5 (ATM6 pack 1.5.0). The bees are unlocked, they left the apiary, pollinated sometimes, only tested tier 1 apiary, I checked logs and didn't find an error. 

I created a new single player world and observed two bees (Lapis and Wither) in a tier 1 apiary for  30 minutes. 

**Lapis bee;** pollinated 3 times then wondered for 3 minutes. Pollinated 4 times then wondered 3 minutes. pollinated 2 times then wondered for 3 minutes. Pollinated once then wondered for 3 minutes. then pollinated 8 times. 

**Wither bee;** pollinated 8 times then wondered  for 3 minutes. Pollinated 10 times.

Both bees went back into the apiary after wondering. I have bees on a server and I know the tier 1 hive has the same issue though I didn't sit and watch them. Hopefully this can help you 😄

**Comment by Epic428** [comment] 2021-02-01 05:38
So bees including vanilla are designed to occasionally wander around. I assume that due to some of the performance changes in the frequency of flower searches and whatnot the wander rate has increased as a result. In either case bees do go in apiaries. And will go in as long as they have nectar/pollen. Once in a while they may randomly go in just because but if they have nectar their priority is finding a hive.

**Comment by Epic428** [comment] 2021-02-01 05:39
Also in response to dawn. 1.16.5 had a few minor bug fixes. So pretty much every mod in 1.16.4 will work with 1.16.5 with no differences.

**Comment by Vaerys-Dawn** [comment] 2021-02-01 05:55
Closing, need more info, not sure if this is a bug, as far as what we can see this is intended behaviour.

**Closed as completed by Vaerys-Dawn** 2021-02-01 05:55 UTC
Labels: 1.16.5
